### ISSUE TITLE
Plugin will not load with my config

### ISSUE THREAD

**Issue by SnowBlitzz** [Yeregorix/SuperPiston#1]
1st error when server starts: https://pastebin.com/tfrQ0gB3

2nd error: https://pastebin.com/nUFZZN5g
if I remove minecraft:end_rod from the config, it will choose another random item to error

My config: https://pastebin.com/Dfwtshss

**Comment by Yeregorix** [comment]
1st error: Use the latest SpongeForge version

2nd error: `minecraft:end_rod` is a BlockType, not a BlockState. For example, you can use `minecraft:end_rod[facing=up]` instead. See https://minecraft.gamepedia.com/Block_states#End_Rod for all possible values. I will try to allow the usage of `BlockType` in the config as soon as I get time.

**Comment by SnowBlitzz** [comment]
If it's not too much to ask, may I request a backport for this plugin for Spongeforge version 3392? Seems very specific but higher versions aren't as stable yet and majority of the Pixelmon community is using this version. The only problem with this particular version is that it has a piston dupe which could be avoided with the use of this plugin so it would be a great help.

**Comment by Yeregorix** [comment]
Here is the backport: [Download](https://files.smoofyuniverse.net/superpiston/SuperPiston-1.0.3-bp1.jar).
